#项目配置
NanKeTop:
  #  项目名称（仅修改反馈及验证码功能的名称，其余请自行查找修改）
  name: "南科Top"
  #  项目地址
  url: ""
  #  数据库URL
  mysql_url: "localhost"
  #  数据库端口
  mysql_port: 3306
  #  数据库名称
  mysql_name: "nanketop"
  #  数据库用户名
  mysql_user: "root"
  #  数据库密码
  mysql_pass: ""
  #  邮箱账号
  email: ""
  #  邮箱授权码
  email_pass: ""
server:
  port: 2150
  tomcat:
    max-http-form-post-size: -1
  address: 0.0.0.0
spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  mail:
    # SMTP服务器
    host: smtp.qq.com
    # 发送验证码邮箱
    username: ${NanKeTop.email}
    # 授权码
    password: ${NanKeTop.email_pass}
    # 编码
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enabled: true
  datasource:
    url:  jdbc:mysql://${NanKeTop.mysql_url}:${NanKeTop.mysql_port}/${NanKeTop.mysql_name}?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${NanKeTop.mysql_user}
    password: ${NanKeTop.mysql_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: classpath:/static,classpath:/templates
mybatis-plus:
  mapper-locations: classpath*:com/nanke/nanketop/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
